services:
  web:
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shopper.rule=Host(`deals.lan`)"
      - "traefik.http.routers.shopper.entrypoints=web"
      - "traefik.http.services.shopper.loadbalancer.server.port=5000"

networks:
  traefik_proxy:
    external: true 